# Generated by Django 4.1.10 on 2024-10-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adovocate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userrname", models.CharField(max_length=50)),
                ("bio", models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
