# Generated by Django 4.1.10 on 2024-10-14 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adovocate",
            old_name="userrname",
            new_name="username",
        ),
    ]
