# Generated by Django 4.1.10 on 2024-10-14 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_rename_userrname_adovocate_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adovocate",
            new_name="Advocate",
        ),
    ]
